// Regenerates test/fsc-parse-failures.txt — the list of corpus files that F#'s
// OWN parser rejects.
//
// The `examples/` corpus is made of real F# repositories, including the F#
// compiler's test suite. A large part of that suite consists of files that are
// *deliberately* malformed (parser error-recovery fixtures, `E_*.fs` tests
// asserting FS0010, ...). tree-sitter reporting an ERROR for those is correct
// behaviour, so counting them as failures hides the real gaps.
//
// Rather than guess from file names, ask FSC: a file is listed here when
// Fantomas.FCS (the compiler's own parser) reports at least one diagnostic with
// Severity=Error and SubCategory="parse". Files that FSC parses cleanly are
// never listed, so no valid test is lost.
//
// Usage (from the repo root):
//     dotnet fsi scripts/find-fsc-parse-failures.fsx
//
// A file is listed only on positive evidence from FSC, so nothing that parses
// as F# is ever hidden. Two consequences worth knowing:
//
//  * No preprocessor symbols are defined, matching a plain compilation, so a
//    syntax error that exists only inside an inactive `#if` branch does not
//    list the file.
//
//  * FSharp.Core's inline IL (`(# "..." #)`) is library-only syntax, not F#
//    proper — a default parser configuration refuses it, so those files are
//    listed too. That is intended: what tree-sitter does with inline IL is
//    unspecified.

#r "nuget: Fantomas.FCS, 7.0.5"

open System.IO
open Fantomas.FCS

let repoRoot = __SOURCE_DIRECTORY__ + "/.."
let corpus = Path.Combine(repoRoot, "examples")
let outputFile = Path.Combine(repoRoot, "test", "fsc-parse-failures.txt")

let relative (path: string) =
    Path.GetRelativePath(repoRoot, path).Replace('\\', '/')

let hasParseError (path: string) =
    try
        let text = File.ReadAllText path
        let _ast, diagnostics = Parse.parseFile false (Text.SourceText.ofString text) []

        diagnostics
        |> List.exists (fun d ->
            d.Severity = Diagnostics.FSharpDiagnosticSeverity.Error
            && d.SubCategory = "parse")
    with e ->
        // A file FSC cannot even read (unsupported encoding, ...) tells us
        // nothing about tree-sitter; leave it in the measured set.
        eprintfn "  skipped %s: %s" (relative path) e.Message
        false

let files =
    Directory.EnumerateFiles(corpus, "*.fs", SearchOption.AllDirectories)
    |> Seq.sort
    |> Seq.toArray

printfn "Parsing %d corpus files with FSC..." files.Length

let failures =
    files
    |> Array.mapi (fun i path ->
        if (i + 1) % 500 = 0 then
            printfn "  %d/%d" (i + 1) files.Length

        path, hasParseError path)
    |> Array.filter snd
    |> Array.map (fst >> relative)

Directory.CreateDirectory(Path.GetDirectoryName outputFile) |> ignore

let lines =
    [| "# Corpus files that F#'s own parser rejects: tree-sitter is expected to"
       "# report an ERROR for these, so parse-all-fs.ps1 skips them."
       "#"
       "# Generated by scripts/find-fsc-parse-failures.fsx - do not edit by hand."
       "# One repo-relative path per line; '#' starts a comment."
       sprintf "# %d of %d corpus files." failures.Length files.Length
       ""
       yield! failures |]

// LF regardless of host OS, matching `* text eol=lf` in .gitattributes, so
// regenerating never shows up as a whole-file diff.
File.WriteAllText(outputFile, String.concat "\n" lines + "\n")

printfn "%d/%d files rejected by FSC -> %s" failures.Length files.Length (relative outputFile)
